In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import geopandas as gpd
import folium
from folium import Marker
from folium.plugins import MarkerCluster,FastMarkerCluster
import dash
from dash import dcc
from dash import html
import base64
import io

In [2]:
df = pd.read_csv('dataset\merged_dataset.csv')

C:\Users\gowda\AppData\Local\Temp\ipykernel_9660\3958433160.py:1: DtypeWarning: Columns (53,54,58,87,90) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('dataset\merged_dataset.csv')

In [44]:
from dash.dependencies import Output, Input
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import re

In [55]:
def clean_distance(distance):
    try:
        distance = re.sub(r'[^0-9]', ' ', distance)
        return distance.strip()
    except:
        return 0

In [59]:

app = dash.Dash(__name__)

In [60]:
app.layout = html.Div([
    html.H1(children='The Victims'),
    dcc.Dropdown(
        id='district-dropdown',
        options=[{'label': i, 'value': i} for i in df['District_Name'].unique()],
        value=df['District_Name'].unique()[0]
    ),
    dcc.Dropdown(
        id='policestation-dropdown'
    ),
    html.Iframe(id='map', srcDoc=open('map.html', 'r').read(), width='80%', height='600'),
    html.Div([
        html.Div([dcc.Graph(id='graph1')], style={'width': '40%', 'display': 'inline-block'}),
        html.Div([dcc.Graph(id='graph2')], style={'width': '40%', 'display': 'inline-block'}),
        html.Div([dcc.Graph(id='graph3')], style={'width': '40%', 'display': 'inline-block'}),
        html.Div([dcc.Graph(id='graph4')], style={'width': '40%', 'display': 'inline-block'}),
        html.Div([dcc.Graph(id='graph5')], style={'width': '40%', 'display': 'inline-block'}),
        html.Div([dcc.Graph(id='graph6')], style={'width': '40%', 'display': 'inline-block'}),
        html.Div([dcc.Graph(id='graph7')], style={'width': '40%', 'display': 'inline-block'}),
        html.Div([dcc.Graph(id='graph8')], style={'width': '40%', 'display': 'inline-block'})
    ]) 
], style={
    'width': '100%',
    'height': '60px',
    'lineHeight': '60px',
    'textAlign': 'center',
    'margin': '10px',
    'backgroundColor': '#86A7FC'
})

@app.callback(
    Output('policestation-dropdown', 'options'),
    Input('district-dropdown', 'value')
)
def update_taluk_dropdown(selected_district):
    policestation = df[df['District_Name'] == selected_district]['UnitName'].unique()
    return [{'label': i, 'value': i} for i in policestation]

@app.callback(
    [Output('map', 'srcDoc'),
    Output('graph1','figure'),
    Output('graph2','figure'),
    Output('graph3','figure'),
    Output('graph4','figure'),
    Output('graph5','figure'),
    Output('graph6','figure'),
    Output('graph7','figure'),
    Output('graph8','figure')],
    [Input('district-dropdown', 'value'),
     Input('policestation-dropdown', 'value')]
)
def update_map(selected_district, selected_taluk):
    filtered_df = df[(df['District_Name'] == selected_district) & (df['UnitName'] == selected_taluk)]
    m = folium.Map(location=[15.3173, 75.7139], tiles='openstreetmap', zoom_start=7)
    m.save('map.html')
    mc = MarkerCluster()
    m = folium.Map(location=[15.3173, 75.7139], tiles='openstreetmap', zoom_start=7)
    for idx,row in filtered_df.iterrows():
        try:
            Marker([row['Latitude'],row['Longitude']]).add_to(mc)
        except:
            pass
    m.add_child(mc)
    m.save('map.html')
    
    filtered_df['age_batch_accused'] = pd.cut(filtered_df['age_x'], bins=[18, 25, 32, 40, 50, 60,100], labels=['18-25', '25-32', '32-40', '40-50', '50-60', '60+'])
    counts1 = filtered_df['age_batch_accused'].value_counts().nlargest(10)
    fig1 = go.Figure(data=go.Bar(x=counts1.index, y=counts1.values, marker_color='skyblue'))
    fig1.update_layout(title_text='Distribution of age of Accused', xaxis_title='Age', yaxis_title='Frequency')

    counts2 = filtered_df['Sex_x'].value_counts().nlargest(2)
    fig2 = go.Figure(data=go.Pie(labels=counts2.index, values=counts2.values))
    fig2.update_layout(title_text='Distribution of Sex of Accused')

    
    filtered_df['age_batch_victim'] = pd.cut(filtered_df['age_y'], bins=[18, 25, 32, 40, 50, 60,100], labels=['18-25', '25-32', '32-40', '40-50', '50-60', '60+'])
    counts3 = filtered_df['age_batch_victim'].value_counts().nlargest(10)
    fig3 = go.Figure(data=go.Bar(x=counts3.index, y=counts3.values, marker_color='skyblue'))
    fig3.update_layout(title_text='Distribution of age of Victim', xaxis_title='Age', yaxis_title='Frequency')

    counts4 = filtered_df['Sex'].value_counts().nlargest(2)
    fig4 = go.Figure(data=go.Pie(labels=counts4.index, values=counts4.values))
    fig4.update_layout(title_text='Distribution of Sex of Victim')
    
    counts5 = filtered_df['FIR Type'].value_counts()
    fig5 = go.Figure(data=go.Pie(labels=counts5.index, values=counts5.values))
    fig5.update_layout(title_text='Distribution of Crime Types')

    counts6 = filtered_df['FIR_Stage'].value_counts().nlargest(5)
    fig6 = go.Figure(data=go.Pie(labels=counts6.index, values=counts6.values))
    fig6.update_layout(title_text='Distribution of FIR Stages')

    counts7 = filtered_df['ActSection'].value_counts().nlargest(10)
    fig7 = go.Figure(data=go.Bar(x=counts7.index, y=counts7.values, marker_color='skyblue'))
    fig7.update_layout(title_text='Distribution of ACT', xaxis_title='Section', yaxis_title='Frequency')
    
    filtered_df['Cleaned_Distance'] = filtered_df['Distance from PS'].apply(clean_distance)
    counts8 = filtered_df['Cleaned_Distance'].value_counts().nlargest(10)
    fig8 = go.Figure(data=go.Bar(x=counts8.index, y=counts8.values, marker_color='skyblue'))
    fig8.update_layout(title_text='Distribution of Distances from police station', xaxis_title='Section', yaxis_title='Frequency')
    
    
    return (open('map.html', 'r').read(),fig1,fig2,fig3,fig4,fig5,fig6,fig7,fig8)

In [61]:
if __name__ == '__main__':
    app.run_server(port = 3001)

In [62]:

df.head()

,District_Name,UnitName,FIRNo,Year,Month,AccusedName,Person_Name,age_x,Caste_x,Profession_x,...,PermanentState_y,Nationality_Name_y,DOB_y,PersonType,InjuryType,Injury_Nature,Crime_No_y,Arr_ID_y,Victim_ID,Cleaned_Distance
0,Bagalkot,Amengad PS,0001/2016,2016,1,YAMxxxxxDAR,YAMANAPPA DURAGAPPA VADDAR,26.0,VADDA,Labourer,...,Karnataka,India,NaN,Deceased,Fatal,NaN,10470124520160001,2016000004,2016000002,12
1,Bagalkot,Amengad PS,0004/2016,2016,1,HUSxxxxxWAR,HUSENAPPA YANKAPPA TALAWAR,30.0,ACHARI,Driver,...,Karnataka,India,NaN,Injured,Fatal,NaN,10470124520160004,2016000016,2016000006,14
2,Bagalkot,Amengad PS,0004/2016,2016,1,HUSxxxxxWAR,HUSENAPPA YANKAPPA TALAWAR,30.0,ACHARI,Driver,...,Karnataka,India,NaN,Injured,Fatal,NaN,10470124520160004,2016000015,2016000005,14
3,Bagalkot,Amengad PS,0004/2016,2016,1,HUSxxxxxWAR,HUSENAPPA YANKAPPA TALAWAR,30.0,ACHARI,Driver,...,Karnataka,India,NaN,Injured,Fatal,NaN,10470124520160004,2016000013,2016000003,14
4,Bagalkot,Amengad PS,0004/2016,2016,1,HUSxxxxxWAR,HUSENAPPA YANKAPPA TALAWAR,30.0,ACHARI,Driver,...,Karnataka,India,NaN,Injured,Fatal,NaN,10470124520160004,2016000014,2016000004,14

C:\Users\gowda\AppData\Local\Temp\ipykernel_9660\4239946068.py:66: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gowda\AppData\Local\Temp\ipykernel_9660\4239946068.py:76: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gowda\AppData\Local\Temp\ipykernel_9660\4239946068.py:97: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gowda\AppData\Local\Temp\ipykernel_9660\4239946068.py:66: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gowda\AppData\Local\Temp\ipykernel_9660\4239946068.py:76: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\gowda\AppData\Local\Temp\ipykernel_9660\4239946068.py:97: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [100]:
import pandas as pd

# Assuming df is your DataFrame and it has columns 'Beat_Name', 'Crime_Count', 'Crime_Against_Women', 'Month'
filtered_df = df[df['UnitName']=="Aldur PS"]
# Calculate total crime count per 'Beat_Name'
beat_crime_count = filtered_df.groupby('Beat_Name')['age_x'].sum()

# Suggest to increase the frequency of the beat if crime count is high
high_crime_beats = beat_crime_count[beat_crime_count > 10]  # Set your own threshold

# Calculate percentage of crime against women per 'Beat_Name'
filtered_df['Women_Crime_Percentage'] = filtered_df.groupby('Beat_Name')['Female'].apply(lambda x: (x.sum() / x.count()) * 100)

# Suggest to include a female staff if crime against women is greater than 10%
beats_need_female_staff = filtered_df[filtered_df['Women_Crime_Percentage'] > -1]['Beat_Name'].unique()

# Calculate crime count per month
month_crime_count = df.groupby('Month')['age_x'].sum()

# Suggest to increase the frequency of beat in the month where crime count is high
high_crime_months = month_crime_count[month_crime_count > 10]  # Set your own threshold

print(f"Beats with high crime: {high_crime_beats}")
print(f"Beats that need female staff: {beats_need_female_staff}")
print(f"Months with high crime: {high_crime_months}")

Beats with high crime: Beat_Name
BEAT NO 01    8748.0
BEAT NO 02    6194.0
BEAT NO 03    6456.0
BEAT NO 04    8167.0
BEAT NO 05    6537.0
BEAT NO 06    4173.0
BEAT NO 07    3521.0
BEAT NO 08     315.0
BEAT NO 09    1037.0
BEAT NO 10    6118.0
BEAT NO 11    8017.0
BEAT NO 12    3070.0
BEAT NO 13    3753.0
BEAT NO 14     717.0
BEAT NO 15     258.0
BEAT NO 16    2268.0
BEAT NO 17     731.0
BEAT NO 18     274.0
BEAT NO 19    1446.0
BEAT NO 20     629.0
BEAT NO 21     679.0
BEAT NO 22     994.0
BEAT NO 23    1168.0
BEAT NO 24     354.0
BEAT NO 25     118.0
BEAT NO 26     428.0
BEAT NO 27     146.0
BEAT NO 28     111.0
BEAT NO 29    2630.0
BEAT NO 30     875.0
BEAT NO 31     455.0
BEAT NO 32     975.0
BEAT NO 33     498.0
Name: age_x, dtype: float64
Beats that need female staff: []
Months with high crime: Month
1     5919756.0
2     5587196.0
3     6183921.0
4     5834075.0
5     6020604.0
6     6037337.0
7     5415086.0
8     5249449.0
9     5223505.0
10    5513815.0
11    5162328.0
12    5509361.0
Name: age_x, dtype: float64

C:\Users\gowda\AppData\Local\Temp\ipykernel_9660\1731171912.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [86]:
df[df['UnitName']=="Aldur PS"]['Beat_Name'].unique()

array(['BEAT NO 02', 'BEAT NO 05', 'BEAT NO 06', 'BEAT NO 03',
       'BEAT NO 07', 'BEAT NO 04', 'BEAT NO 10', 'BEAT NO 01',
       'BEAT NO 14', 'BEAT NO 13', 'BEAT NO 17', 'BEAT NO 19',
       'BEAT NO 16', 'BEAT NO 20', 'BEAT NO 23', 'BEAT NO 12',
       'BEAT NO 31', 'BEAT NO 09', 'BEAT NO 21', 'BEAT NO 18',
       'BEAT NO 27', 'BEAT NO 26', 'BEAT NO 32', 'BEAT NO 08',
       'BEAT NO 22', 'BEAT NO 29', 'BEAT NO 11', 'BEAT NO 24',
       'BEAT NO 33', 'BEAT NO 15', 'BEAT NO 30', 'BEAT NO 25',
       'BEAT NO 28'], dtype=object)